### PR TITLE
Separate ctlr & f12 options

### PR DESCRIPTION
**Pull request by HDVinnie**
Separate ctlr & f12 options for better flexibility

### CODE REVIEW

**Comment by HDVinnie** [comment]
this is a repush of @the94air original PR which I think is a good one

**Comment by the94air** [comment]
Thanks, this is a breaking change so.. it should be on version 2 @PHPJunior .

**Comment by the94air** [comment]
@HDVinnie it looks like this package is not maintained anymore. You can merge the pull request in a fork and require it on the composer.

**Comment by the94air** [comment]
Thanks anyways ¯\_(ツ)_/¯

**Pull request closed without merging**
